const express=require("express");
const cors=require("core");
require("dotenv").config();
const activitiesRoutes=require("./routes/activities");
const absencesRoutes=require("./routes/absences");
const reportsRoutes=require("./routes/reports");
const app=express();
app.use(cors());
app.use(express.json());
app.use("/api/activities",activitiesRoutes);
app.use("/api/absences",absencesRoutes);
app.use("/api/reports",reportsRoutes);
app.listen(5000,()=>console.log("Server running on http://localhost:5000"));